### ISSUE TITLE
Is it possible to create a finite wall?

### ISSUE THREAD

**Issue by lee-liu** [markus-ebke/python-billiards#4]
Hi, currently in the project there is an obstacle class for infinite wall, but if I want to create an arbitrarily shaped table (like a polygon table), the infinite wall cannot do this. So, I wonder if there can be a way to create a finite wall class (given the starting and end point just like the infinite one)? I've tried to modify the code by calculating the intersection between the ball's trajectory and the infinite wall, and change the infinite one into a finite one, but I haven't success.

**Comment by markus-ebke** [comment]
Hello, thank you for your interest in my work. This project is quite simple at the moment, and if I have some free time in the future I want to add more features like finite walls.
To answer your question: It is possible to implement finite walls (or polygons) as just another obstacles class, but I think this is much harder because of the endpoints. A ball can hit the wall at the wall segment, miss it completely, or hit it at one of the endpoints. In the latter case I couldn't figure out a good way to calculate the time of impact and the direction in which the ball would bounce.
The same applies to the corners of a polygon.
![image](https://user-images.githubusercontent.com/43856989/122667040-b9396c00-d1eb-11eb-8e7b-06b8de85d07f.png)

**Comment by markus-ebke** [comment]
In version 1.0 I added a LineSegment obstacle. Collisions with the end-points are resolved as if the ends are rounded.
